sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
- pip install tox-travis flake8
#- pip install -r requirements.txt
script:
- flake8
#- tox
#after_success:
#- bash <(curl -s https://codecov.io/bash)